### ISSUE TITLE
Develop branch Time class calling mallocr instead of malloc

### ISSUE THREAD

**Issue by wesner0019** [spark/firmware#521] opened 2015-08-07 14:41 UTC
[quote="peekay123, post:17, topic:14113, full:true"]
https://community.particle.io/t/local-building-does-not-compile-with-warnings/14113/13
Folks, it turns out that sbrk() is called by functions in the Time class which are calling mallocr instead of malloc.  When @mdma gets back, he should be able to fix this quickly.  This only affects the develop branch.
[/quote]

**Comment by bprobbins** [comment] 2015-08-07 23:39
Just git pulled today on the latest branch and found that the sbrk bug now afflicting the latest branch today as well

**Comment by technobly** [comment] 2015-08-10 15:57
FWIW: I tried replacing localtime() with localtime_r() and it still requires _sbrk(), but it might be worth considering using the reentrant safe version of localtime anyway.

**Comment by m-mcgowan** [comment] 2015-08-10 20:27
afaik, localtime() calls localtime_r(), and that's true for all standard and re-entrant functions, the standard function calls the re-entrant one using a global context.

**Comment by m-mcgowan** [comment] 2015-08-11 02:24
Duplicate of #503.

**Closed by m-mcgowan** 2015-08-11 02:24 UTC
Labels: bug
