### ISSUE TITLE
Compilation error with ARM GCC 5.4.1 20160609

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#1085] opened 2016-08-09 20:22 UTC
In the modules directory:

```
% git checkout v0.5.1
HEAD is now at a0791d1... tweak version info for 0.5.1
% PLATFORM=photon APP=tinker make -s clean all
  /Users/zac/code/particle/firmware/modules/photon/system-part1/makefile /Users/zac/code/particle/firmware/modules/photon/system-part2/makefile /Users/zac/code/particle/firmware/modules/photon/user-part/makefile
In file included from ./src/photon/wiced/network/LwIP/WWD/FreeRTOS/arch/cc.h:69:0,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/arch.h:43,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/debug.h:35,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/opt.h:46,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/ipv4/lwip/ip_addr.h:35,
                 from ./src/photon/wiced/network/LwIP/WICED/wiced_network.h:43,
                 from ./src/photon/include/wiced_tcpip.h:44,
                 from ./src/photon/include/wiced.h:46,
                 from src/photon/core_hal.c:28:
./src/photon/wiced/network/LwIP/WWD/FreeRTOS/cpu.h:43:0: error: "BYTE_ORDER" redefined [-Werror]
 #define BYTE_ORDER LITTLE_ENDIAN
 ^
In file included from /usr/local/gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/sys/types.h:67:0,
                 from /usr/local/gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/stdio.h:48,
                 from ./src/photon/wiced/WWD/include/wwd_debug.h:40,
                 from ./src/photon/wiced/WWD/include/wwd_assert.h:42,
                 from ./src/photon/wiced/RTOS/FreeRTOS/WWD/ARM_CM3/FreeRTOSConfig.h:41,
                 from ./src/photon/wiced/RTOS/FreeRTOS/ver7.5.2/Source/include/FreeRTOS.h:78,
                 from ./src/photon/wiced/RTOS/FreeRTOS/WWD/wwd_rtos.h:46,
                 from ./src/photon/wiced/WWD/include/RTOS/wwd_rtos_interface.h:47,
                 from ./src/photon/wiced/platform/MCU/STM32F2xx/peripherals/platform_mcu_peripheral.h:56,
                 from ./src/photon/wiced/platform/include/platform_peripheral.h:42,
                 from ./src/photon/include/wiced_platform.h:46,
                 from ./src/photon/include/wiced.h:44,
                 from src/photon/core_hal.c:28:
/usr/local/gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/machine/endian.h:20:0: note: this is the location of the previous definition
 #define BYTE_ORDER _BYTE_ORDER
 ^
cc1: all warnings being treated as errors
make[2]: *** [../build/target/hal/platform-6-m/./src/photon/core_hal.o] Error 1
make[1]: *** [hal] Error 2
make: *** [/Users/zac/code/particle/firmware/modules/photon/system-part1/makefile] Error 2

% arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also see #1084.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by m-mcgowan** [comment] 2016-09-13 18:25
Duplicate of #1054

**Closed** 2016-11-29 04:53 UTC
