### ISSUE TITLE
Photon with SSID out of range, 7 second delay between loop() invocations?

### ISSUE THREAD

**Issue by projectgus** [spark/firmware#604] opened 2015-09-11 07:04 UTC
I'm moving an application from Spark Core to Photon for a client. They've been using Cores in a situation where the WiFi network is not always present. They use  `SYSTEM_MODE(SEMI_AUTOMATIC)` to run some code immediately after reset, then call Particle.connect() from `setup()`.

The Photon port seems to be working fine (after applying other changes), as long as the WiFi access point is available.

As soon as the WiFi network isn't found, we're seeing a 7 second gap (as measured with `millis()`) between each invocation of `loop()` - I'm guessing as the Photon scans for SSIDs each time around and waits for the response?

This happens when the SSID is unavailable from reset, I haven't tested whether it also happens when the SSID goes away while the Photon is associated  to it.

On the Core there was no significant delay between `loop()` invocations that we noticed.

Is this a known issue? Is there anything we can do to mitigate it? I've tried building against the current latest branch (0.4.4?) and develop branch (0.4.5rc2?), both seem to have the same behaviour.

**Comment by m-mcgowan** [comment] 2015-09-11 10:46
This is a known issue. I have an app that shows the same behavior. The cause is that the wifi calls are asynchronous on the cc3000 but synchornous on WICED.

The future fix is to use multithreading to run the application on a separate thread. A beta of this will be available next week.

**Comment by projectgus** [comment] 2015-09-14 05:49
Thank you for the update.

We've worked around the issue for now by moving almost all the interactive behaviour to a timer interrupt, but will be eagerly awaiting the threading support so we can undo that!

**Comment by m-mcgowan** [comment] 2015-09-30 07:25
Confirmed that multithreading beta will be released with 0.4.6, which addresses this issue.

**Closed by m-mcgowan** 2015-09-30 07:25 UTC
