### ISSUE TITLE
Spark.syncTime() gives compile error with Photon

### ISSUE THREAD

**Issue by JimBob2015** [spark/firmware#431] opened 2015-05-31 03:57 UTC
This function compiles and executes OK when compiled for a Core but gives an error message when compiling for a Photon.

**Comment by m-mcgowan** [comment] 2015-05-31 07:41
Duplicate of https://github.com/spark/firmware/issues/426 - the issue is fixed and will be in the next release.

**Closed** 2015-05-31 12:04 UTC
