### ISSUE TITLE
Core subscribing to own events causes multiple problems

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#371] opened 2014-12-31 11:02 UTC
In this thread I stumbled across a HardFault, unreliable `Spark.subscribe` and near impossible OTA flashing when a Core tries to subscribe to its own `Spark.publish` events (public publish & open subscribe)

http://community.spark.io/t/how-to-transfer-data-between-2-cores/9050/10

**Comment by kennethlimcp** [comment] 2015-01-05 14:55
@ScruffR, using the test code from: http://community.spark.io/t/how-to-transfer-data-between-2-cores/9050/14, the results seems positive and subscribing to your events works great but not at high rates.

**Comment by ScruffR** [comment] 2015-01-05 15:30
I still think that publish/subscribe ought to be more robust and shouldn't get messed up by merely one line  of the ubiquitous `delay()` function.

**Comment by dmiddlecamp** [comment] 2015-01-05 15:32
@ScruffR - I think this has more to do with the tcp / cc3000 stack on the Core than the pub/sub system in particular.  The core isn't multi-threaded, so hard delays prevent it from checking for received messages.  One workaround we've been talking about is just running the wlan loop more often during long delays.,

**Comment by kennethlimcp** [comment] 2015-01-05 15:32
agreed but being single-threaded on the core...it's like wanting to pub and sub almost simultaneously that makes it unstable. It would be nice for some priority cases etc... @dmiddlecamp :hand:

**Comment by ScruffR** [comment] 2015-01-05 15:37
@dmiddlecamp, but I got the impression this was why `delay()` has been adapted to account for the cloude house keeping needs in the early days of the Cores arrival.
And therefore I wouldn't have expected this behaviour.

**Comment by dmiddlecamp** [comment] 2015-01-05 15:43
Right, I think delay will turn the crank once every second or so, but that's not necessarily enough for sending and receiving many messages.  I'm working on a version that spends most of the delay in the wlan loop, and less time fully blocked, which I think could be a workaround in the short-term.

**Comment by ScruffR** [comment] 2015-01-05 16:20
That would be good and I'm sure it'll work as a workaround.
But in my test code I didn't actually send or receive many events (one every two sec), so I'd rather see it as you said yourself as a race condition between publish and subscribe.
Prioritising as @kennethlimcp suggested would be a nice idea, or as a quickfix just making publish/subscribe handling "mutually exclusive" per iteration of `SPARK_WLAN_Loop` even calls do all the publishing odd ones all the subscriptions.

**Comment by m-mcgowan** [comment] 2015-01-05 16:26
I imagine this could be related to issue #272, which I'm investigating.

**Comment by m-mcgowan** [comment] 2015-04-06 00:06
I tried this out using the latest code from feature/hal (private repo) and upgraded to CC3000 service pack 1.32 (from cc3000-patch-programmer repo):

- no red SOSs after 5 minutes. 
- see published events using the spark-cli, 
- successfully performed OTA update

The only issue is that the devices didn't get any events via their subscription.
I thought maybe an issue with self-subscription, but when I run the code on 2 devices simultaneously, neither see any events. Unclear at present what the cause of this is.

**Comment by m-mcgowan** [comment] 2015-09-27 11:43
@ScruffR - do you have chance to test this using the latest 1.14/1.32 CC3000 service pack?

**Comment by ScruffR** [comment] 2015-09-27 13:16
Sure, can I use `particle flash --usb cc3000_1_14` or do I have to build it and use dfu?

**Comment by m-mcgowan** [comment] 2015-09-27 13:31
Yeah thats correct. I forgot you can flash it from cli.

**Comment by ScruffR** [comment] 2015-09-27 14:30
OK, my first tests (with 0.4.5) do not show any red flashes and OTA update works very reliably (given the current cloud reconnect problems)

One thing that's not too much of a problem but counter-intuitive at least. 
In case 3 (PRIVATE publish and subscribe to DEVICE_ID) the handler doesn't get triggered.

```
void setup()
{
    Serial.begin(115200);
    Particle.subscribe("publicScruff", handler);
    Particle.subscribe("privateScruff", handler, MY_DEVICES);
    Particle.subscribe("ScruffyMe", handler, "53ff72065067544856321287");
}


int i;
void loop()
{
    char nr[24];


    i++;
    sprintf(nr, "%5d < %5d >",i%4, i);
    switch(i % 4)
    {
        case 0:
            Particle.publish("publicScruff", nr);
            break;
        case 1:
            Particle.publish("privateScruff", nr, PRIVATE);
            break;
        case 2:
            Particle.publish("ScruffyMe", nr);
            break;
        case 4:
            Particle.publish("ScruffyMe", nr, PRIVATE);
            break;
        default:
            break;
    }
    
    delay(1000);
}

void handler(const char* event, const char* data)
{
    char str[256];
    sprintf(str, "%s: %s", event, data);
    Serial.println(str);
}
```

**Comment by m-mcgowan** [comment] 2015-09-27 14:33
Many thanks for this. I'm not sure if device-specific subscriptions are supported in the cloud just yet. @dmiddlecamp would know for sure.

**Comment by ScruffR** [comment] 2015-09-27 14:53
When published PUBLIC the device subscription works (case 2).

Also tested 0.3.4, and it works without OTA problems and red flashes

But the handler triggers differently again :wink: 
Core 0.3.4 case 0, 2, 3 work - case 1 does not
Core 0.4.5 case 0, 1, 2, work - case 3 does not

I think I'll have to check some other combinations too now.

**Comment by ScruffR** [comment] 2015-09-27 15:08
Checking these cases now
```
    switch(i % cases)
    {
        case 0:
            Spark.publish("publicScruff", nr);
            break;
        case 1:
            Spark.publish("privateScruff", nr, PRIVATE);
            break;
        case 2:
            Spark.publish("ScruffyMe", nr);
            break;
        case 3:
            Spark.publish("ScruffyMe", nr, PRIVATE);
            break;
        case 4: 
            // private handler should still trigger my own devices 
            // (even if publicly published)
            Spark.publish("privateScruff", nr);
            break;
        case 5: 
            // public hanlder should not be triggered by private event
            Spark.publish("publicScruff", nr, PRIVATE);
            break;
        default:
            break;
    }
```

For 0.3.4 cases 0, 2, 3, 5 work - 1, 4 not
For 0.4.5 cases 0, 1, 2, work - 3, 4, 5, not

A similar test for the Photon might be necessary too - and a matrix which combinations of PUBLIC/PRIVATE events should trigger which subscriptions (PUBLIC, MY_DEVICES, DEVICE_ID).
I think I'll open a new issue for this.

**Comment by m-mcgowan** [comment] 2015-09-28 11:38
Since the original SOS is fixed, I'll close this so we can focus our efforts on the inconsistencies mentioned.

**Closed by m-mcgowan** 2015-09-28 11:38 UTC
